---
- name: Configure users in MariaDB
  hosts: mariadb_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Create users and set password if not present
      mysql_user:
        name: "{{ item['name']  }}"
        password: "{{ item['password'] }}"
        update_password: on_create
        state: present
      loop: "{{ mysql_user_passwords }}"
      no_log: true

    - name: Configure users in MariaDB for all databases
      mysql_user:
        name: "{{ item['name'] }}"
        host: "{{ item['host'] }}"
        priv: "{{ item['priv'] }}"
        state: "{{ item['state'] }}"
      loop: "{{ mysql_users }}"

    - name: Update users with password for all host
      mysql_user:
        name: "{{ item['name'] }}"
        host_all: yes
        update_password: always
        password: "{{ item['password'] }}"
        state: present
      loop: "{{ mysql_user_passwords }}"
      no_log: true
