---
- name: Install MariadDB server
  hosts: mariadb_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Install mariadb-server pgk
      yum:
        name: mariadb-server
        state: present

    - name: Enable and start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Firewall permits mysql service
      firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: yes
