---
- name: haproxy
  hosts: mariadb_servers
  become: true
  tasks:
    - name: install haproxy
      yum:
        name: haproxy
        state: present
    - name: copy haproxy.cfg.j2
      template:
        src: files/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      
    - name: start haproxy and enabled
      service:
        name: haproxy
        state: started
        enabled: yes
     

