---
- name: Set up SSH key-based authentication
  hosts: all
  become: true

  tasks:
    - name: Copy SSH public key to authorized_keys file
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

